<?php

namespace Ron\ConsumptionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConsumptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsumptionRepository extends EntityRepository
{
}
