<?php

namespace Ron\ConsumptionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WaterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaterRepository extends EntityRepository
{
}
