avr_net_io_homepage:
    pattern:  /
    defaults: { _controller: RonRaspberryPiBundle:Default:showInput }
avr_set_port:
    pattern: /setport/{port}/{value}
    defaults: { _controller: RonRaspberryPiBundle:Default:setPort }
avr_output:
    pattern:  /output
    defaults: { _controller: RonRaspberryPiBundle:Default:avrOutput }
avr_info:
    pattern: /info
    defaults: { _controller: RonRaspberryPiBundle:Default:avrInfo }
rpi_input:
    pattern: /input
    defaults: { _controller: RonRaspberryPiBundle:Default:showInput }
avr_output_temp_image:
    pattern: /output/temperature/image/{period}
    defaults: { _controller: RonRaspberryPiBundle:Default:outputTemperatureImage }
avr_output_temp:
    pattern: /output/temperature
    defaults: { _controller: RonRaspberryPiBundle:Default:avrOutputTemperature }
_login:
    pattern: /login
    defaults: { _controller: RonRaspberryPiBundle:Secured:login }
_logout:
    pattern: /logout
    defaults: { _controller: RonRaspberryPiBundle:Secured:logout }
_login_check:
    pattern: /login_check
    defaults: { _controller: RonRaspberryPiBundle:Secured:loginCheck }
_connection_fail:
    pattern: /connectionFail
    defaults: { _controller: RonRaspberryPiBundle:Default:connectionFail }
ron_raspberry_pi_homepage:
    pattern:  /rpi
    defaults: { _controller: RonRaspberryPiBundle:Default:index }
ron_raspberry_pi_pir_image:
    pattern: /output/motion/image/{period}
    defaults: { _controller: RonRaspberryPiBundle:Pir:outputPirImage }
ron_raspberry_pi_pir:
    pattern: /output/motion/{period}
    defaults: { _controller: RonRaspberryPiBundle:Pir:outputPir }
ron_raspberry_pi_pirs:
    pattern: /output/motion
    defaults: { _controller: RonRaspberryPiBundle:Pir:pirs }
ron_raspberry_pi_switch:
    pattern: /switch
    defaults: { _controller: RonRaspberryPiBundle:Switch:index }
ron_raspberry_pi_timer_start:
    pattern: /timer_start
    defaults: { _controller: RonRaspberryPiBundle:Switch:startTimer }