parameters:
    pir.image.path: '/home/pi/motion'
    avr.enabled: false
    ebay_temp_dir: "/tmp"
    raspi_switch_code: "10001"
#    ron_raspberry_pi.example.class: Ron\RaspberryPiBundle\Example

services:
    ron_sun_helper:
        class: Ron\RaspberryPiBundle\Lib\Sun
        arguments: [ %location_latitude%, %location_longitude%]
#    ron_raspberry_pi.example:
#        class: %ron_raspberry_pi.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
