parameters:
#    temperature.image.path: '/home/pi/temperature'
    avr.ip: "192.168.178.178"
    avr.port: "50290"

services:
    avr:
        class: Ron\AvrNetIoBundle\Avr\AvrNetIo
        arguments: ["%avr.ip%", "%avr.port%"]
