parameters:
    temperature.image.path: '/home/pi/temperature'
#    ron_consumption.example.class: Ron\ConsumptionBundle\Example

services:
#    ron_consumption.example:
#        class: %ron_consumption.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
